[[constraint]]
  name = "github.com/Financial-Times/go-fthealth"
  version = "0.4.0"

[[constraint]]
  name = "github.com/Financial-Times/message-queue-gonsumer"
  version = "0.4.0"

[[constraint]]
  name = "github.com/Financial-Times/service-status-go"
  version = "0.1.0"

[[constraint]]
  name = "github.com/Financial-Times/uuid-utils-go"
  version = "1.0.1"

[[constraint]]
  name = "github.com/Sirupsen/logrus"
  version = "0.11.2"

[[constraint]]
  name = "github.com/coreos/etcd"
  version = "3.1.2"

[[constraint]]
  branch = "master"
  name = "github.com/giantswarm/retry-go"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.3.0"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "1.1.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.1.4"

[prune]
  go-tests = true
  unused-packages = true
