apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.service.name }}
  labels:
    chart: "{{ .Chart.Name | trunc 63 }}"
    chartVersion: "{{ .Chart.Version | trunc 63 }}"
    app: {{ .Values.service.name }}
    visualize: "true"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.service.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.service.name }}
        visualize: "true"
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - {{ .Values.service.name }}
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: {{ .Values.service.name }}
        image: "{{ .Values.image.repository }}:{{ .Chart.Version }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
{{ toYaml .Values.resources | indent 12 }}
        env:
        - name: ENVIRONMENT
          value: "{{ .Values.envs.environment }}"
        - name: KAFKA_TOPIC
          value: "{{ .Values.envs.kafka_topic }}"
        - name: KAFKA_PROXY_HOST
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: kafka.proxy.url
        - name: QUEUE_ADDR
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: kafka.proxy.url.with.protocol
        - name: CONTENT_URL
          value: "{{ .Values.envs.content_url }}"
        - name: CONTENT_NEO4J_URL
          value: "{{ .Values.envs.content_neo4j_url }}"
        - name: CONTENT_COLLECTION_NEO4J_URL
          value: "{{ .Values.envs.content_collection_neo4j_url }}"
        - name: COMPLEMENTARY_CONTENT_URL
          value: "{{ .Values.envs.complementary_content_url }}"
        - name: INTERNAL_COMPONENTS_URL
          value: "{{ .Values.envs.internal_components_url }}"
        - name: LISTS_URL
          value: "{{ .Values.envs.lists_url }}"
        - name: PAGES_URL
          value: "{{ .Values.envs.pages_url }}"
        - name: NOTIFICATIONS_URL
          value: {{ .Values.envs.notifications_url }}\&{{ .Values.envs.notifications_url_param2 }}
        - name: NOTIFICATIONS_PUSH_URL
          value: {{ .Values.envs.notifications_push_url }}\&{{ .Values.envs.notifications_push_url_param2 }}\&{{ .Values.envs.notifications_push_url_param3 }}\&{{ .Values.envs.notifications_push_url_param4 }}
        - name: LIST_NOTIFICATIONS_URL
          value: "{{ .Values.envs.list_notifications_url }}"
        - name: LIST_NOTIFICATIONS_PUSH_URL
          value: "{{ .Values.envs.list_notifications_push_url }}"
        - name: LIST_NOTIFICATIONS_PUSH_API_KEY
          valueFrom:
            secretKeyRef:
              name: publish-availability-monitor-secrets
              key: list_notifications_push.api_key
        - name: PAGE_NOTIFICATIONS_PUSH_URL
          value: "{{ .Values.envs.page_notifications_push_url }}"
        - name: PAGE_NOTIFICATIONS_PUSH_API_KEY
          valueFrom:
            secretKeyRef:
              name: publish-availability-monitor-secrets
              key: page_notifications_push.api_key
        - name: NOTIFICATIONS_PUSH_API_KEY
          valueFrom:
            secretKeyRef:
              name: publish-availability-monitor-secrets
              key: notifications_push.api_key
        - name: GRAPHITE_ADDRESS
          value: "{{ .Values.envs.graphite_address }}"
        - name: GRAPHITE_UUID
          valueFrom:
            secretKeyRef:
              name: publish-availability-monitor-secrets
              key: graphite.uuid
        {{- $base_url := default .Values.cluster.delivery.url .Values.envs.validation_endpoints.base_url }}
        - name: VIDEO_MAPPER_URL
          value: "{{ $base_url }}/{{ .Values.envs.validation_endpoints.video_mapper }}"
        - name: WORDPRESS_MAPPER_URL
          value: "{{ $base_url }}/{{ .Values.envs.validation_endpoints.wordpress_mapper }}"
        - name: UPP_INTERNAL_ARTICLE_VALIDATOR_URL
          value: "{{ $base_url }}/{{ .Values.envs.validation_endpoints.upp_internal_article_validator }}"
        - name: UPP_LIST_VALIDATOR_URL
          value: "{{ $base_url }}/{{ .Values.envs.validation_endpoints.upp_list_validator }}"
        - name: UPP_PAGE_VALIDATOR_URL
          value: "{{ $base_url }}/{{ .Values.envs.validation_endpoints.upp_page_validator }}"
        - name: UPP_INTERNAL_CPH_VALIDATOR_URL
          value: "{{ $base_url }}/{{ .Values.envs.validation_endpoints.upp_internal_cph_validator }}"
        - name: UPP_IMAGE_VALIDATOR_URL
          value: "{{ $base_url }}/{{ .Values.envs.validation_endpoints.upp_image_validator }}"
        - name: UPP_IMAGE_SET_VALIDATOR_URL
          value: "{{ $base_url }}/{{ .Values.envs.validation_endpoints.upp_image_set_validator }}"
        - name: UPP_GRAPHIC_VALIDATOR_URL
          value: "{{ $base_url }}/{{ .Values.envs.validation_endpoints.upp_graphic_validator }}"
        - name: UPP_CONTENT_COLLECTION_VALIDATOR_URL
          value: "{{ $base_url }}/{{ .Values.envs.validation_endpoints.upp_content_collection_validator }}"
        - name: UPP_INTERNAL_LIVE_BLOG_PACKAGE_VALIDATOR_URL
          value: "{{ $base_url }}/{{ .Values.envs.validation_endpoints.upp_internal_live_blog_package_validator }}"
        - name: UPP_INTERNAL_LIVE_BLOG_POST_VALIDATOR_URL
          value: "{{ $base_url }}/{{ .Values.envs.validation_endpoints.upp_internal_live_blog_post_validator }}"
        - name: UPP_AUDIO_VALIDATOR_URL
          value: "{{ $base_url }}/{{ .Values.envs.validation_endpoints.upp_audio_validator }}"
        ports:
        - containerPort: 8080
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 30
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 30
        volumeMounts:
        - name: read-envs-config
          mountPath: {{ .Values.volumes.read_envs_config_mount_path }}
        - name: pam-secrets
          mountPath: {{ .Values.volumes.secrets_mount_path }}
      volumes:
      - name: pam-secrets
        secret:
          secretName: publish-availability-monitor-secrets
          items:
          - key: read-credentials
            path: {{ .Values.volumes.read_env_credentials_file_name }}
          - key: validator-credentials
            path: {{ .Values.volumes.validation_credentials_file_name }}
      - name: read-envs-config
        configMap:
          name: global-config
          items:
          - key: pam.read.environments
            path: {{ .Values.volumes.read_envs_config_file_name }}

# corresponding secret template
# kind: Secret
# apiVersion: v1
# metadata:
#   name: publish-availability-monitor-secrets
#   namespace: default
# data:
#   read-credentials:
# [
#   {
#     "env-name": "k8s",
#     "username": "foo",
#     "password": "bar"
#   }
# ]
#
#   validator-credentials:
# {
#   "username": "oof",
#   "password": "baz"
# }
#
#  list_notifications_push.api_key: fooBar
#  notifications_push.api_key: foobaz
