# Values used for the deployed application.
replicaCount: 1
service:
  name: publish-availability-monitor
envs:
  kafka_topic: "PreNativeCmsPublicationEvents"
  content_url: "/__document-store-api/content/"
  content_neo4j_url: "/__content-rw-neo4j/content/"
  complementary_content_url: "/__document-store-api/complementarycontent/"
  internal_components_url: "/__document-store-api/internalcomponents/"
  lists_url: "/__document-store-api/lists/"
  notifications_url: "/__notifications-rw/content/notifications?type=all"
  # I had to split the URL into 2 parts because I couldn't find a way to put the exact string \& in the value
  # This way I moved handling that value in the template chart where it seems it doesn't have a problem with it.
  notifications_push_url:  "/content/notifications-push?monitor=true"
  notifications_push_url_param2: "type=all"
  lists_notifications_url: "/__list-notifications-rw/lists/notifications"
  lists_notifications_push_url: "/lists/notifications-push?monitor=true"
  validation_endpoints:
    methode_article_mapper: "__methode-article-mapper/map"
    methode_content_placeholder_mapper: "__methode-content-placeholder-mapper/map"
    methode_image_model_mapper: "__methode-image-model-mapper/map"
    methode_list_mapper: "__methode-list-mapper/map"
    methode_article_internal_components_mapper: "__methode-article-internal-components-mapper/map"
    video_mapper: "__upp-next-video-mapper/map"
    wordpress_mapper: "__wordpress-article-mapper/map"
    # base_url is provided on install by the pipeline
    base_url: ""
  uuid_resolver_url: "/__document-store-api"
