# Values used for the deployed application.
replicaCount: 1
service:
  name: publish-availability-monitor
  accountName: eksctl-publish-availability-monitor-serviceaccount
envs:
  environment: "dev"
  kafka_topic: "PreNativeCmsPublicationEvents"
  kafka_consumer_group: "publish-availability-monitor"
  kafka_lag_tolerance: 120
  log_level: "INFO"
  content_url: "/__document-store-api/content/"
  content_neo4j_url: "/__content-rw-neo4j/content/"
  content_collection_neo4j_url: "/__content-collection-rw-neo4j/content-collection/content-package/"
  complementary_content_url: "/__document-store-api/complementarycontent/"
  internal_components_url: "/__document-store-api/internalcomponents/"
  lists_url: "/__public-lists-api/lists/"
  pages_url: "/__public-pages-api/pages/"
  notifications_url: "/__notifications-rw/content/notifications?type=all"
  notifications_url_param2: "monitor=true"
  # I had to split the URL into 2 parts because I couldn't find a way to put the exact string \& in the value
  # This way I moved handling that value in the template chart where it seems it doesn't have a problem with it.
  notifications_push_url:  "/content/notifications-push?monitor=true"
  notifications_push_url_param2: "type=all"
  notifications_push_url_param3: "type=LiveBlogPackage"
  notifications_push_url_param4: "type=LiveBlogPost"
  list_notifications_url: "/__list-notifications-rw/lists/notifications"
  list_notifications_push_url: "/lists/notifications-push?monitor=true"
  page_notifications_url: "/__page-notifications-rw/pages/notifications"
  page_notifications_push_url: "/pages/notifications-push?monitor=true"
  validation_endpoints:
    video_mapper: "__upp-next-video-mapper/map"
    upp_internal_article_validator: "__upp-internal-article-validator/validate"
    upp_list_validator: "__upp-list-validator/validate"
    upp_page_validator: "__upp-page-validator/validate"
    upp_internal_cph_validator: "__upp-internal-content-placeholder-validator/validate"
    upp_image_validator: "__upp-image-validator/validate"
    upp_image_set_validator: "__upp-image-set-validator/validate"
    upp_graphic_validator: "__upp-graphic-validator/validate"
    upp_content_collection_validator: "__upp-content-collection-validator/validate"
    upp_internal_live_blog_package_validator: "__upp-internal-live-blog-package-validator/validate"
    upp_internal_live_blog_post_validator: "__upp-internal-live-blog-post-validator/validate"
    upp_audio_validator: "__upp-audio-validator/validate"
    upp_clip_validator: "__upp-clip-validator/validate"
    upp_clip_set_validator: "__upp-clip-set-validator/validate"
    upp_content_relation_validator: "__upp-content-relation-validator/validate"
    upp_custom_code_component_validator: "__upp-custom-code-component-validator/validate"

cluster:
  delivery:
    url: "https://upp-k8s-dev-delivery-eu.upp.ft.com"

