# Default values for Publish Availability Monitor.
service:
  name: "" # The name of the service, should be defined in the specific app-configs folder.
  hasHealthcheck: "true"
replicaCount: 1
image:
  repository: coco/publish-availability-monitor
  pullPolicy: Always
envs:
  kafka_topic: ""
  content_url: ""
  complementary_content_url: ""
  internal_components_url: ""
  lists_url: ""
  pages_url: ""
  notifications_url: ""
  notifications_push_url: ""
  list_notifications_url: ""
  list_notifications_push_url: ""
  page_notifications_push_url: ""
  validation_endpoints:
    video_mapper_endpoint: ""
    wordpress_mapper_endpoint: ""
    base_url: ""
  uuid_resolver_url: ""
  graphite_address: "graphitev2.ft.com:2003"
volumes:
  read_envs_config_mount_path: "/etc/pam/envs"
  secrets_mount_path: "/etc/pam/credentials"
  read_env_credentials_file_name: "read-environments-credentials.json"
  validation_credentials_file_name: "validator-credentials.json"
  read_envs_config_file_name: "read-environments.json"
resources:
  limits:
    memory: 512Mi
  requests:
    memory: 256Mi

